=== rap1ds/vr-practice/DoubleWallExample/data/coordcfg.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://ruisystem.net/coordcfg"
	xmlns:tns="http://ruisystem.net/coordcfg" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<element name="coordinateCalibration" type="tns:CoordinateCalibrationType"></element>
	
	<complexType name="CoordinateCalibrationType">
	 <sequence>
	   <element name="kinectCoordinatesOrigin" type="tns:KinectCoordinatesOriginType"/>
	   <element name="moveCoordinatesOrigin" type="tns:MoveCoordinatesOrigin"/>
	   <element name="transformFromKinectToMove" type="tns:TransformFromKinectToMove"></element>
	 </sequence>
	</complexType>
	
	<complexType name="KinectCoordinatesOriginType">
	 <sequence>
	   <element name="translate" type="tns:TranslateType"/>
	   <element name="rotate" type="tns:RotateType"></element>
	 </sequence>
	</complexType>
	
	 <complexType name="MoveCoordinatesOrigin">
   <sequence>
     <element name="translate" type="tns:TranslateType"/>
     <element name="rotate" type="tns:RotateType"></element>
   </sequence>
  </complexType>
  
    <complexType name="TransformFromKinectToMove">
   <sequence>
     <element name="translate" type="tns:TranslateType"/>
     <element name="rotate" type="tns:RotateType"></element>
   </sequence>
  </complexType>

	<complexType name="TranslateType">
		<attribute name="x"  />
		<attribute name="y" />
		<attribute name="z" />
	</complexType>
	
	 <complexType name="RotateType">
    <attribute name="r00" type="float" use="required"/>
    <attribute name="r01" type="float" use="required"/>
    <attribute name="r02" type="float" use="required"/>
    <attribute name="r10" type="float" use="required"/>
    <attribute name="r11" type="float" use="required"/>
    <attribute name="r12" type="float" use="required"/>
    <attribute name="r20" type="float" use="required"/>
    <attribute name="r21" type="float" use="required"/>
    <attribute name="r22" type="float" use="required"/>
  </complexType>
  
</schema>

=== rap1ds/vr-practice/DoubleWallExample/data/coordinateCalibration.xml
<coordinateCalibration     xmlns="http://ruisystem.net/coordcfg"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://ruisystem.net/coordcfg coordcfg.xsd">

	<kinectCoordinatesOrigin>
		<translate x="0.0" y="0.0" z="0.0" />
		<rotate r00="1.0" r01="0.0" r02="0.0" r10="0.0" r11="1.0" r12="0.0"

			r20="0.0" r21="0.0" r22="1.0" />

	</kinectCoordinatesOrigin>

	<moveCoordinatesOrigin>
		<translate x="0.0" y="0.0" z="0.0" />
		<rotate r00="1.0" r01="0.0" r02="0.0" r10="0.0" r11="1.0" r12="0.0"

			r20="0.0" r21="0.0" r22="1.0" />

	</moveCoordinatesOrigin>
	<transformFromKinectToMove>
		<translate x="0.0" y="0.0" z="0.0" />
		<rotate r00="1.0" r01="0.0" r02="0.0" r10="0.0" r11="1.0" r12="0.0"
			r20="0.0" r21="0.0" r22="1.0" />
	</transformFromKinectToMove>
</coordinateCalibration>
