=== rap1ds/vr-practice/DoubleWallExample/data/displaycfg.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns:sharedcfg="http://ruisystem.net/sharedcfg"
        targetNamespace="http://ruisystem.net/displaycfg" 
        xmlns:displaycfg="http://ruisystem.net/displaycfg" 
        elementFormDefault="qualified"
        attributeFormDefault="unqualified">
  <import namespace="http://ruisystem.net/sharedcfg"
          xsi:schemaLocation="http://ruisystem.net/sharedcfg sharedcfg.xsd"/>
          
  <element name="viewManager" type="displaycfg:ViewManagerType"/>
  
  <complexType name="ViewManagerType">
    <sequence>
    <!-- TODO: maximum displays allowed? -->
      <element name="display" type="displaycfg:DisplayType" minOccurs="1" maxOccurs="8"></element>
    </sequence>
    <attribute name="stereoEyeDistance" type="float" default="6.0"></attribute>
    <attribute name="defaultCameraX" type="float" default="0.0"></attribute>
    <attribute name="defaultCameraY" type="float" default="0.0"></attribute>
    <attribute name="defaultCameraZ" type="float" default="0.0"></attribute>
  </complexType>
  
  <complexType name="DisplayType">
    <sequence>
      <element name="center" type="displaycfg:CartesianType"/>
      <element name="up" type="displaycfg:CartesianType"/>
      <element name="normal" type="displaycfg:CartesianType"/>
    </sequence>
    <attribute name="width" type="float"/>
    <attribute name="height" type="float"/>
    <attribute name="stereo" type="boolean"/>
  </complexType>
  
  <complexType name="CartesianType">
    <attributeGroup ref="displaycfg:XYZGroup"></attributeGroup>
  </complexType>
  
  <attributeGroup name="XYZGroup">
    <attribute name="x" type="float" default="0"></attribute>
    <attribute name="y" type="float" default="0"></attribute>
    <attribute name="z" type="float" default="0"></attribute>
  </attributeGroup>
  
</schema>

=== rap1ds/vr-practice/DoubleWallExample/data/displayConfig.xml
<viewManager 
    xmlns="http://ruisystem.net/displaycfg"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://ruisystem.net/displaycfg displaycfg.xsd"
    defaultCameraX="0.0" defaultCameraY="0.0" defaultCameraZ="300.0"
    stereoEyeDistance="6.0">
    <display width="300.0" height="300.0" stereo="false"> 
        <center x="0.0" y="0.0" z="0.0" />
        <up     x="0.0"  y="-1.0"  z="0.0" />
        <normal x="0.0"   y="0.0"   z="1.0" />
    </display>
    <display width="300.0" height="300.0" stereo="false"> 
        <center x="150.0" y="0.0" z="150.0" />
        <up     x="0.0"   y="-1.0"  z="0.0" />
        <normal x="-1.0"  y="0.0"   z="0.0" />
    </display>
	<!-- It is possible to have any number of displays.  
		 If stereo="false", Xth display's parameters are mapped to 
		 viewManager.keystonedScreen[X-1]. If stereo="true", Xth display's
		 parameters are mapped to viewManager.keystonedScreen[Y-1] and
		 mapped to viewManager.keystonedScreen[Y], where Y is the total 
		 number of keystonedWall instances that were created by other
		 display elements of this file before the Xth display element.     -->
</viewManager>
